# Generated by Django 4.2.1 on 2023-06-05 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('contact_number', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Max_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QC_max', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('SC_max', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('PC_max', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Principal_Investigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('lab_tel', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scid', models.CharField(default=None, max_length=11, unique=True)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('申請單編號', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('serum', models.IntegerField(blank=True, default=0, null=True)),
                ('CBC', models.IntegerField(blank=True, default=0, null=True)),
                ('excel_file', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.CharField(blank=True, max_length=255, null=True)),
                ('pay', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sc_contact', to='form.contact')),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sc_pi', to='form.principal_investigator')),
            ],
            options={
                'verbose_name': '血液血清手開單',
                'verbose_name_plural': '血液血清手開單',
            },
        ),
        migrations.CreateModel(
            name='QC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qcid', models.CharField(default=None, max_length=11, unique=True)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('mus_number', models.IntegerField(blank=True, default=0, null=True)),
                ('rat_number', models.IntegerField(blank=True, default=0, null=True)),
                ('excel_file', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.CharField(blank=True, max_length=255, null=True)),
                ('pay', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_contact', to='form.contact')),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_pi', to='form.principal_investigator')),
            ],
            options={
                'verbose_name': '健康監測手開單',
                'verbose_name_plural': '健康監測手開單',
            },
        ),
        migrations.CreateModel(
            name='PC_OUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_out_id', models.CharField(default=None, max_length=11, unique=True)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('申請單編號', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('excel_file', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.CharField(blank=True, max_length=255, null=True)),
                ('pay', models.BooleanField(default=False)),
                ('A', models.IntegerField(blank=True, default=0, null=True)),
                ('B', models.IntegerField(blank=True, default=0, null=True)),
                ('C', models.IntegerField(blank=True, default=0, null=True)),
                ('D', models.IntegerField(blank=True, default=0, null=True)),
                ('E', models.IntegerField(blank=True, default=0, null=True)),
                ('F', models.IntegerField(blank=True, default=0, null=True)),
                ('G', models.IntegerField(blank=True, default=0, null=True)),
                ('H', models.IntegerField(blank=True, default=0, null=True)),
                ('I', models.IntegerField(blank=True, default=0, null=True)),
                ('J', models.IntegerField(blank=True, default=0, null=True)),
                ('K', models.IntegerField(blank=True, default=0, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_ous_contact', to='form.contact')),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_ous_pi', to='form.principal_investigator')),
            ],
            options={
                'verbose_name': '組織切片校外手開單',
                'verbose_name_plural': '組織切片校外手開單',
            },
        ),
        migrations.CreateModel(
            name='PC_INS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_ins_id', models.CharField(default=None, max_length=11, unique=True)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('申請單編號', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('excel_file', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.CharField(blank=True, max_length=255, null=True)),
                ('pay', models.BooleanField(default=False)),
                ('A', models.IntegerField(blank=True, default=0, null=True)),
                ('B', models.IntegerField(blank=True, default=0, null=True)),
                ('C', models.IntegerField(blank=True, default=0, null=True)),
                ('D', models.IntegerField(blank=True, default=0, null=True)),
                ('E', models.IntegerField(blank=True, default=0, null=True)),
                ('F', models.IntegerField(blank=True, default=0, null=True)),
                ('G', models.IntegerField(blank=True, default=0, null=True)),
                ('H', models.IntegerField(blank=True, default=0, null=True)),
                ('I', models.IntegerField(blank=True, default=0, null=True)),
                ('J', models.IntegerField(blank=True, default=0, null=True)),
                ('K', models.IntegerField(blank=True, default=0, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_ins_contact', to='form.contact')),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_ins_pi', to='form.principal_investigator')),
            ],
            options={
                'verbose_name': '組織切片校內手開單',
                'verbose_name_plural': '組織切片校內手開單',
            },
        ),
        migrations.CreateModel(
            name='PC_IND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_ind_id', models.CharField(default=None, max_length=11, unique=True)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('申請單編號', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('excel_file', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.CharField(blank=True, max_length=255, null=True)),
                ('pay', models.BooleanField(default=False)),
                ('A', models.IntegerField(blank=True, default=0, null=True)),
                ('B', models.IntegerField(blank=True, default=0, null=True)),
                ('C', models.IntegerField(blank=True, default=0, null=True)),
                ('D', models.IntegerField(blank=True, default=0, null=True)),
                ('E', models.IntegerField(blank=True, default=0, null=True)),
                ('F', models.IntegerField(blank=True, default=0, null=True)),
                ('G', models.IntegerField(blank=True, default=0, null=True)),
                ('H', models.IntegerField(blank=True, default=0, null=True)),
                ('I', models.IntegerField(blank=True, default=0, null=True)),
                ('J', models.IntegerField(blank=True, default=0, null=True)),
                ('K', models.IntegerField(blank=True, default=0, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_ind_contact', to='form.contact')),
            ],
            options={
                'verbose_name': '組織切片產業價手開單',
                'verbose_name_plural': '組織切片產業價手開單',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.principal_investigator'),
        ),
    ]
