# Generated by Django 4.2.1 on 2023-05-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PC_IND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('pi', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('lab_tel', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('contact', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('A', models.IntegerField(blank=True, default=0, null=True)),
                ('B', models.IntegerField(blank=True, default=0, null=True)),
                ('C', models.IntegerField(blank=True, default=0, null=True)),
                ('D', models.IntegerField(blank=True, default=0, null=True)),
                ('E', models.IntegerField(blank=True, default=0, null=True)),
                ('F', models.IntegerField(blank=True, default=0, null=True)),
                ('G', models.IntegerField(blank=True, default=0, null=True)),
                ('H', models.IntegerField(blank=True, default=0, null=True)),
                ('I', models.IntegerField(blank=True, default=0, null=True)),
                ('J', models.IntegerField(blank=True, default=0, null=True)),
                ('K', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PC_INS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('pi', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('lab_tel', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('contact', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('A', models.IntegerField(blank=True, default=0, null=True)),
                ('B', models.IntegerField(blank=True, default=0, null=True)),
                ('C', models.IntegerField(blank=True, default=0, null=True)),
                ('D', models.IntegerField(blank=True, default=0, null=True)),
                ('E', models.IntegerField(blank=True, default=0, null=True)),
                ('F', models.IntegerField(blank=True, default=0, null=True)),
                ('G', models.IntegerField(blank=True, default=0, null=True)),
                ('H', models.IntegerField(blank=True, default=0, null=True)),
                ('I', models.IntegerField(blank=True, default=0, null=True)),
                ('J', models.IntegerField(blank=True, default=0, null=True)),
                ('K', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PC_OUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('pi', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('lab_tel', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('contact', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('A', models.IntegerField(blank=True, default=0, null=True)),
                ('B', models.IntegerField(blank=True, default=0, null=True)),
                ('C', models.IntegerField(blank=True, default=0, null=True)),
                ('D', models.IntegerField(blank=True, default=0, null=True)),
                ('E', models.IntegerField(blank=True, default=0, null=True)),
                ('F', models.IntegerField(blank=True, default=0, null=True)),
                ('G', models.IntegerField(blank=True, default=0, null=True)),
                ('H', models.IntegerField(blank=True, default=0, null=True)),
                ('I', models.IntegerField(blank=True, default=0, null=True)),
                ('J', models.IntegerField(blank=True, default=0, null=True)),
                ('K', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('pi', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('lab_tel', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('contact', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('mice', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('pi', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('lab_tel', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('contact', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('serum', models.IntegerField(blank=True, default=0, null=True)),
                ('bloodcell', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
