# Generated by Django 4.2.1 on 2023-05-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Max_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QC_max', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('SC_max', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('PC_max', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pc_ind',
            name='pc_indid',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='pc_ins',
            name='pc_insid',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='pc_ous',
            name='pc_outid',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='qc',
            name='max_qcid',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qc',
            name='qcid',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='sc',
            name='scid',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
