# Generated by Django 4.2.1 on 2023-05-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_max_id_pc_ind_pc_indid_pc_ins_pc_insid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qc',
            name='max_qcid',
        ),
    ]
