# Generated by Django 4.2.1 on 2023-06-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc',
            name='discount',
            field=models.CharField(blank=True, default='100%', max_length=6, null=True),
        ),
    ]
