# Generated by Django 4.2.1 on 2023-05-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_qc_max_qcid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qc',
            old_name='mice',
            new_name='number',
        ),
        migrations.AddField(
            model_name='qc',
            name='contact_tel',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
