# Generated by Django 4.2.1 on 2023-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_qc_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc',
            name='discount',
            field=models.CharField(blank=True, default='100%', max_length=6, null=True),
        ),
    ]
