# Generated by Django 4.2.1 on 2023-05-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_rename_mice_qc_number_qc_contact_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_ind',
            name='contact_tel',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pc_ins',
            name='contact_tel',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pc_ous',
            name='contact_tel',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sc',
            name='contact_tel',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
