# Generated by Django 4.2.1 on 2023-06-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_remove_pc_ins_申請單編號_pc_ins_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc_ind',
            name='申請單編號',
        ),
        migrations.RemoveField(
            model_name='pc_ous',
            name='申請單編號',
        ),
        migrations.AddField(
            model_name='pc_ind',
            name='discount',
            field=models.CharField(blank=True, default='100%', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='pc_ous',
            name='discount',
            field=models.CharField(blank=True, default='100%', max_length=6, null=True),
        ),
    ]
