# Generated by Django 4.2.1 on 2023-05-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_pc_ind_contact_tel_pc_ins_contact_tel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pc_ind',
            old_name='pc_indid',
            new_name='pcid',
        ),
        migrations.RenameField(
            model_name='pc_ins',
            old_name='pc_insid',
            new_name='pcid',
        ),
        migrations.RenameField(
            model_name='pc_ous',
            old_name='pc_outid',
            new_name='pcid',
        ),
    ]
