# Generated by Django 4.2.1 on 2023-07-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_remove_pc_ind_申請單編號_remove_pc_ous_申請單編號_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_id', models.CharField(default=None, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('discount', models.CharField(blank=True, default='100%', max_length=6, null=True)),
                ('excel_file', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.CharField(blank=True, max_length=255, null=True)),
                ('pay', models.BooleanField(default=False)),
                ('A', models.IntegerField(blank=True, default=0, null=True)),
                ('B', models.IntegerField(blank=True, default=0, null=True)),
                ('C', models.IntegerField(blank=True, default=0, null=True)),
                ('D', models.IntegerField(blank=True, default=0, null=True)),
                ('E', models.IntegerField(blank=True, default=0, null=True)),
                ('F', models.IntegerField(blank=True, default=0, null=True)),
                ('G', models.IntegerField(blank=True, default=0, null=True)),
                ('H', models.IntegerField(blank=True, default=0, null=True)),
                ('I', models.IntegerField(blank=True, default=0, null=True)),
                ('J', models.IntegerField(blank=True, default=0, null=True)),
                ('K', models.IntegerField(blank=True, default=0, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_contact', to='form.contact')),
            ],
            options={
                'verbose_name': '校內月結',
                'verbose_name_plural': '校內月結',
            },
        ),
    ]
