# Generated by Django 4.2.1 on 2023-05-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_rename_pc_indid_pc_ind_pcid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pc_ind',
            options={'verbose_name': '組織切片產業價手開單', 'verbose_name_plural': '組織切片產業價手開單'},
        ),
        migrations.AlterModelOptions(
            name='pc_ins',
            options={'verbose_name': '組織切片校內手開單', 'verbose_name_plural': '組織切片校內手開單'},
        ),
        migrations.AlterModelOptions(
            name='pc_ous',
            options={'verbose_name': '組織切片校外手開單', 'verbose_name_plural': '組織切片校外手開單'},
        ),
        migrations.AlterModelOptions(
            name='qc',
            options={'verbose_name': '健康監測手開單', 'verbose_name_plural': '健康監測手開單'},
        ),
        migrations.AlterModelOptions(
            name='sc',
            options={'verbose_name': '血液血清手開單', 'verbose_name_plural': '血液血清手開單'},
        ),
    ]
