# Generated by Django 4.2.1 on 2023-07-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_monthly_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_settlement',
            name='申請單編號',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
