# Generated by Django 4.2.1 on 2023-05-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_pc_ind_options_alter_pc_ins_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sc',
            name='scid',
            field=models.CharField(default='2023QC000', max_length=10, unique=True),
        ),
    ]
