# Generated by Django 4.2.1 on 2023-07-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_monthly_settlement_申請單編號'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_settlement',
            name='pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_pi', to='form.principal_investigator'),
        ),
    ]
