# Generated by Django 4.2.1 on 2023-07-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_monthly_settlement_pi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monthly_settlement',
            new_name='MS',
        ),
    ]
