# Generated by Django 4.2.1 on 2023-07-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0010_rename_monthly_settlement_ms"),
    ]

    operations = [
        migrations.AddField(
            model_name="qc",
            name="tax",
            field=models.BooleanField(default=False),
        ),
    ]
