# Generated by Django 4.2.1 on 2023-07-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0011_qc_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="sc",
            name="tax",
            field=models.BooleanField(default=False),
        ),
    ]
