# Generated by Django 4.2.1 on 2023-05-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_rename_pcid_pc_ind_pc_ind_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
