# Generated by Django 4.2.1 on 2023-07-31 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0012_sc_tax"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pcid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pcid", models.CharField(default=None, max_length=11, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="pc_ins",
            name="pc_ins_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="form.pcid"
            ),
        ),
    ]
