# Generated by Django 4.2.1 on 2023-05-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_qc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
