# Generated by Django 4.2.1 on 2023-05-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_qc_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_ind',
            name='pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pc_ins',
            name='pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pc_ous',
            name='pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sc',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
