# Generated by Django 4.2.1 on 2023-05-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_pc_ind_pay_pc_ins_pay_pc_ous_pay_sc_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc_ind',
            name='pc_ind_id',
            field=models.CharField(default=None, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='pc_ins',
            name='pc_ins_id',
            field=models.CharField(default=None, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='pc_ous',
            name='pc_out_id',
            field=models.CharField(default=None, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='qc',
            name='qcid',
            field=models.CharField(default=None, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='sc',
            name='scid',
            field=models.CharField(default=None, max_length=11, unique=True),
        ),
    ]
