# Generated by Django 4.2.1 on 2023-07-31 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0014_alter_pc_ins_pc_ins_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pc_ind",
            name="pc_ind_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="form.pcid"
            ),
        ),
        migrations.AlterField(
            model_name="pc_ous",
            name="pc_out_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="form.pcid"
            ),
        ),
    ]
