# Generated by Django 4.2.1 on 2023-05-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_alter_pc_ind_pc_ind_id_alter_pc_ins_pc_ins_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc_ind',
            name='lab_tel',
        ),
        migrations.RemoveField(
            model_name='pc_ind',
            name='pi',
        ),
    ]
