# Generated by Django 4.2.1 on 2023-08-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0016_alter_pcid_options_ms_l_pc_ind_l_pc_ins_l_pc_ous_l"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pc_ind",
            name="discount",
        ),
        migrations.AddField(
            model_name="pc_ind",
            name="tax",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pc_ins",
            name="tax",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pc_ous",
            name="tax",
            field=models.BooleanField(default=False),
        ),
    ]
