# Generated by Django 4.2.1 on 2023-05-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_pc_ind_file_pc_ins_file_pc_ous_file_sc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_ind',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pc_ins',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pc_ous',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='qc',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sc',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
