# Generated by Django 4.2.1 on 2023-05-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_pc_ind_description_pc_ins_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_ind',
            name='申請單編號',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pc_ins',
            name='申請單編號',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pc_ous',
            name='申請單編號',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sc',
            name='申請單編號',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
