# Generated by Django 4.2.1 on 2023-05-31 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0019_pc_ind_申請單編號_pc_ins_申請單編號_pc_ous_申請單編號_sc_申請單編號'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sc',
            old_name='bloodcell',
            new_name='CBC',
        ),
    ]
